Update to MoorDyn v2
WEC-Sim/WEC-Sim pull request #1134
Opened 2023-10-02 18:09 UTC by RyanDavies19

This updated the coupling of WECSim and MoorDyn to MoorDyn-C v2 using the MoorDyn v1 API. Additional updates to the MoorDyn libraries and input files will be added separately. 

The only new feature added is the ability to specify the path and file name of the MoorDyn input file. This will be the same path where outputs are written. The figures below show that this update performs as well as the MoorDyn v1 coupling. This update opens the door to future utilization of the MoorDyn v2 features. 

![Fairten_comp](https://github.com/WEC-Sim/WEC-Sim/assets/101124339/4e0af9bb-8c29-46e0-9c9a-6b5489d6686c)
![float_heave_response](https://github.com/WEC-Sim/WEC-Sim/assets/101124339/ccc2fa7f-2ac2-4df5-82dd-f6a292de3a69)
![float_surge_response](https://github.com/WEC-Sim/WEC-Sim/assets/101124339/56099324-b3ed-4c61-aef5-b28e0de22be3)
![spar_heave_response](https://github.com/WEC-Sim/WEC-Sim/assets/101124339/a1fd01f4-8d68-467b-8598-feebcce467fb)
![spar_surge_response](https://github.com/WEC-Sim/WEC-Sim/assets/101124339/7a3d0422-d1ac-4d23-8713-77fbe178d4ff)

2023-10-02 19:39 UTC, jtgrasb commented
Corresponds with [WEC-Sim Applications PR 45 ](https://github.com/WEC-Sim/WEC-Sim_Applications/pull/45) and [WEC-Sim/MoorDyn PR 1](https://github.com/WEC-Sim/MoorDyn/pull/1).

2023-10-02 21:54 UTC, akeeste requested changes
@jtgrasb @RyanDavies19 Thanks for your work. It's great to see updates for MoorDyn in WEC-Sim! After installing MinGW and adding ``WEC-Sim/MoorDyn`` to the source, the applications case runs to completion.

A few requested changes:
- [x] Update responseClass.m line 347 to account for new output file naming
   - I received several messages that "No moorDyn *.out file saved for Line1", etc (These should probably be warnings). However there are output files located in ``CASE/Mooring/`` with names ``lines_Line1.out``, etc. It looks like the name of the MoorDyn input file is being appended to all output files. We should account for this. The case still runs when the responseClass is updated
- [x] Update the variable name of ``moorDyn_infile`` to WEC-Sim's camelCase convention. I suggest ``moorDynInputFile``
- [ ] Please briefly note here what changes were made to the Mooring library for our future reference. It appears changes are primarily in the ``Properties/Callbacks`` of ``WECSim_Lib_Moorings/MoorDyn/MoorDyn/MoorDyn``. Anything else of note?

A couple other non-critical comments for future work:
* Where in the MoorDyn repo do the files in ``WEC-Sim/MoorDyn`` come from? As an alternative to copying files to WEC-Sim/MoorDyn and then to the WEC-Sim source, could users point straight to a local MoorDyn clone?
* We should add that information to the developer manual

2023-10-02 22:17 UTC, jtgrasb commented
Thanks for the review @akeeste. I updated accordingly. 

The updates to the mooring library are only in the ``Properties/Callbacks`` of ``WECSim_Lib_Moorings/MoorDyn/MoorDyn/MoorDyn``. These updates changed the initFcn, stopFcn, and closeFcn to use the new library name ('libmoordyn') and the new MoorDyn.h header file which serves as a wrapper for MoorDyn.

2023-10-04 16:32 UTC, akeeste commented on source/objects/mooringClass.m
> +        libname (1,:) {mustBeText} = 'libmoordyn'                         % (`string`) Name of the mooring. Default = ``'NOT DEFINED'``
I don't see this variable used anywhere else. Can we remove it?

2023-10-04 16:33 UTC, akeeste commented
Thanks @jtgrasb @RyanDavies19 for the updates and comments. I missed one thing in my review on ``libname``, see above

2023-10-04 16:34 UTC, RyanDavies19 commented
@akeeste you can remove that libname variable. That was left over from a different approach we were trying, I forgot to remove it.

2023-10-04 16:37 UTC, akeeste commented
@RyanDavies19 sounds good. I'll merge this PR and fix it on dev

2023-10-04 16:37 UTC, merged