New pto sim lib
WEC-Sim/WEC-Sim pull request #821
Opened 2022-03-09 17:33 UTC by jleonqu

New PR to solve some conflicts in the previous PR #743

2022-03-10 20:06 UTC, kmruehl commented
@jleonqu there are merge conflicts with this PR now that PR #803 has been merged, and it looks like there are files revised here that you didn't mean to include. Let's go through this together during the WEC-Sim working meeting tomorrow.

2022-03-14 19:41 UTC, kmruehl commented
@jleonqu looks great, thanks for resolving the merge conflicts with dev! @akeeste thanks for your help!

2022-03-14 21:13 UTC, kmruehl requested changes
@jleonqu this is looking good and I think we should prioritize merging it and opening another PR for further revisions. 
These revisions should be made prior to merge:

- [x] Please delete this file: `source/lib/PTO-Sim/BlockFigures/PTOSim_Lib.slx`
- [x] This file should not be empty, please revert: `source/objects/ptoClass.m`

2022-03-14 21:13 UTC, kmruehl commented on docs/user/code_structure.rst
> +
This should be `.. _user-code-structure-ptosim-class:`

2022-03-14 21:13 UTC, kmruehl commented on source/objects/ptoSimClass.m
> +            'Rload'                           ,'NOT DEFINED')               % External load
These properties should be camelCase

2022-03-14 23:13 UTC, jleonqu commented
@kmruehl I am not sure about the second comment "This file should not be empty, please revert: source/objects/ptoClass.m", this is the file I currently have in the PR: [ptoClass.m](https://github.com/jleonqu/WEC-Sim/blob/NewPTOSimLib/source/objects/ptoClass.m)

2022-03-15 21:48 UTC, kmruehl commented
That's strange, this is what the review is showing on my end:
![image](https://user-images.githubusercontent.com/4603379/158478269-fb0c8256-fc44-4192-af7c-2557b8244e5a.png)

Nothing should have been updated in the `ptoClass`, correct?

2022-03-15 22:36 UTC, kmruehl commented
@jleonqu I'd like to merge this into dev but now there are some merge conflicts, can you resolve them?

2022-03-15 23:06 UTC, jleonqu commented
@kmruehl I have resolved the conflicts

2022-03-16 21:55 UTC, kmruehl approved these changes
Thanks @jleonqu!

2022-03-16 22:19 UTC, merged